baseURL = "http://example.org/"
languageCode = "en-us"
title = "Arketa"
theme = "arketa"
copyright = "Copyright Sabu Siyad"

paginate = 3

PygmentsStyle = "nord"
PygmentsCodeFences = true
PygmentsCodeClasses = true
PygmentsCodeFencesGuessSyntax = true

# googleAnalytics = "UA-123-45"

summaryLength = 20

[params]
	mode = "auto" # "dark", "auto", "light"
   logo = "/logo.jpg"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Instagram"
icon = "logo-instagram"
url = "https://github.com/vividvilla/ezhil"

[[params.social]]
name = "Twitter"
icon = "logo-twitter"
url = "https://github.com/vividvilla/ezhil"

[[params.social]]
name = "Github"
icon = "logo-github"
url = "https://github.com/vividvilla/ezhil"

[[params.social]]
name = "RSS"
icon = "logo-rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
